apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: pyapi
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: pyapi
    tier: frontend
