---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: pyapi
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapi
      tier: frontend
  template:
    metadata:
      labels:
        app: pyapi
        tier: frontend
    spec:
      containers:
      - name: pyapi
        image: gtechnology/pyapi:latest
        ports:
---
apiVersion: v1
kind: Service
metadata:
  name: front-ingress
  labels:
    app: pyapi
spec:
  selector:
    app: pyapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
